### PR TITLE
Add Ohne I/O

### PR DESCRIPTION
**Pull request by acatton**
I wasn't sure where and how to put it.

Lemme know if this needs to be restructured.

### CODE REVIEW

**Comment by Lukasa** [comment]
Hi @acatton, thanks for this!

Before adding this, I think it would be good to have a document to link to that concisely demonstrates the sans-IO nature of this library. There are a lot of `yield from ohneio.read()` and `yield from ohneio.write()` that can easily be mistaken for mixing I/O directly in to your parser, which is exactly what sans I/O recommends *not* doing.

**Comment by acatton** [comment]
Thanks for your quick answer @Lukasa, I'm not sure what this document would look like. Do you have any suggestion, I thought the README was self explanatory, but the fact that you are confused demonstrates that it is not. I'm always open to improve it, or write something.

Thanks.

**Comment by Lukasa** [comment]
@acatton Well, let's put it another way.

My *understanding* of what the README shows is that it is essentially a coroutine-based wrapper for a pair of in-memory buffers that allows you to use `send` and `read` to insert/remove data from the buffers, along with a number of helpers that allow `yield from` to handle data in those buffers.

However, that's not obvious from the README. In fact, the README says "ohneio allows you to write protocol parsers the way you would write an asyncio protocol", which is a little confusing because you wouldn't write an [`asyncio.Protocol`](https://docs.python.org/3/library/asyncio-protocol.html#protocols) that way in normal use.

What I think you need, then, is an explanation of how this works and the expected programming style. Essentially, you need a narrative justification that lays out the following:

1. How is this different from doing I/O? (Answer: the reads and writes are to/from in-memory buffers, with the `yield from` syntax essentially hiding read/write conditions for those buffers).
2. How do you integrate this with actual I/O? (Bonus points: do it with non-asyncio I/O to prove that there is no actual asyncio requirement, despite the programming style appearing like there is.)
3. What advantages does this have over manual buffer management?

For sans-io's part, we then need to consider whether we are going to list all tools that are helpful with designing I/O-free libraries. I'm open to it, but that potentially opens the floodgates to a *lot* of libraries. Maybe that's what we should have, though.

**Comment by acatton** [comment]
Thanks @Lukasa, I'll write a small chapter in the docs http://ohneio.rtfd.io/ to explain all of this. You made a *lot* of good suggestions here. I'll post a comment with a link on this pull request once this is done.

Second of all, regarding the libraries helpful to design I/O-free library, I would love to have them listed because the first reason I wrote Ohne I/O in the first place was because it looks like this space was empty. But I could be wrong, and as someone who wants to develop an sans-io protocol library (In my case AMQP), that will be insightful to have a list of helping library.

**Comment by brettcannon** [comment]
In regards to listing support libraries, we can start with them in a sub-section and then see where it goes. If it becomes too much then we take the section out.

**Comment by Lukasa** [comment]
Cool, that sounds good. Let's try to keep the focus tight on things that specifically help with managing I/O and patterns. We can consider later if we want to expand to other useful things.

**Comment by brettcannon** [comment]
OK, so why don't we do this:

1. @acatton updates his docs for Ohne to make it bit clearer that the library is to up with sans-IO libraries and he pings this PR when that's done
2. Under `Implementations` we add`Protocols` and `Support Libraries` (we could add a sentence specifying what is acceptable, although saying "managing I/O" on the sans-IO page might make people do a double-take :smile: )
3. We make Ohne the initial library listed under `Support Libraries`

**Pull request closed without merging**
