### PR TITLE
Add oauthlib's implementation of IO-less OAuth 1.0 and 2.0

### PR DESCRIPTION
**Pull request by mahmoud**
Per [the discussion on Twitter](https://twitter.com/brettsky/status/762421870553464832), here's a PR that adds @idan's wonderful oauthlib. Thanks for collecting these, hope to see many more!

### CODE REVIEW

**Comment by brettcannon** [comment]
@Lukasa any input on this PR?

**Comment by Lukasa** [comment]
So I understand your uncertainty here @brettcannon, it's reasonable to argue that OAuth isn't a protocol in the same way that, e.g. HTTP and FTP are. However, I think hopping over to oauthlib's README provides a good enough case for adding it via its point 3: "[Other libraries] assume the usage of a specific HTTP request library."

Additionally, OAuth really kinda *is* a protocol: it's just one that happens to be tunnelled over HTTP. But to say that OAuth is to HTTP as HTTP is to TCP is not entirely unreasonable: OAuth just happens to be a very formalised method to transfer certain bits of data around while making certain assertions about ownership and integrity and stuff.

So I think I'm tentatively +1, although it definitely adds a *soupçon* of ambiguity to the message of the page. If we find ourselves getting buried in "higher-level-than-HTTP" modules we can reconsider the page structure I think.

**Comment by brettcannon** [comment]
I'm going w/ @Lukasa 's +0. We will claw back the page if we end up buried under SOAP/XML-RPC/JSON-RPC/whatever libraries.

**Comment by idan** [comment]
I think this fits nicely with your stated mission; thank you for featuring OAuthlib!

**Pull request merged**
